#!/usr/bin/env bash
# Shared config and helpers, sourced by every script in this chain.
#
# Target-agnostic: how nodes are created and reached comes from
# $CLUSTER_TARGET/lib/target.sh - local/ (multipass VMs on this machine) or
# remote/ (already-provisioned servers over ssh). The scripts in those two
# folders set CLUSTER_TARGET; the shared steps in steps/ only ever go
# through the interface below, so they run unchanged against either.
#
# Target interface (see local/lib/target.sh, remote/lib/target.sh):
#   TARGET_CP_SCRIPT, TARGET_WORKERS_SCRIPT - the target's 00 / 02 scripts,
#                                  named in error messages
#   target_require               - checks the target's own host tools
#   cp_node                      - the control plane's node name
#   worker_nodes                 - the existing worker nodes, one per line
#   node_exists <node>
#   node_ip <node>               - the IPv4 address this machine reaches it on
#   cp_swarm_addr                - the address workers reach the control
#                                  plane on (Swarm's advertise address)
#   node_wait_ready <node>       - blocks until it's reachable and cloud-init
#                                  (if any) is done
#   node_run <node> <cmd...>     - runs a command as root there, uncapped,
#                                  with stdin/stdout passed through
#   node_copy <file> <node> <path> - copies a local file there
#   node_hint <node>             - how a person runs a root command there,
#                                  for error messages
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

case "${CLUSTER_TARGET:-}" in
  local|remote) ;;
  *) echo "CLUSTER_TARGET must be 'local' or 'remote' (got '${CLUSTER_TARGET:-}') — run the scripts in local/ or remote/, not steps/ directly" >&2
     exit 1 ;;
esac
TARGET_DIR="$ROOT_DIR/$CLUSTER_TARGET"

DOKPLOY_PORT=3000
REGISTRY_PORT=5000
OPENBAO_PORT=8200

# Everything the chain generates is tied to one cluster, so it lives per
# target: a local test cluster and a remote one never overwrite each other's
# keys. Gitignored. local/teardown.sh and remote/forget.sh remove it.
STATE_DIR="$ROOT_DIR/.state/$CLUSTER_TARGET"
mkdir -p "$STATE_DIR"
chmod 700 "$ROOT_DIR/.state" "$STATE_DIR"
# Dokploy's API key. Written by 01-dokploy-api-key.sh.
API_KEY_FILE="$STATE_DIR/dokploy-api-key"
# Generated by 03-setup-registry.sh.
REGISTRY_CREDS_FILE="$STATE_DIR/registry-credentials"
# OpenBao's init response (root token, recovery key). Written by
# 05-setup-openbao.sh.
OPENBAO_INIT_FILE="$STATE_DIR/openbao-init.json"
# The web app's first admin. Generated by 07-deploy-web-app.sh.
WEB_APP_CREDS_FILE="$STATE_DIR/web-app-credentials"

require() {
  for cmd in "$@"; do
    command -v "$cmd" >/dev/null 2>&1 || { echo "missing required command: $cmd" >&2; exit 1; }
  done
}

env_file_value() {
  # env_file_value <file> <key> - extract KEY=value from a simple env file
  # WITHOUT sourcing/executing it. A strong random password can easily
  # contain shell-special characters ($, !, `, etc.) - `source`-ing the
  # file would let bash try to interpret those instead of treating the
  # value as plain text. Only strips one layer of matching "..."/'...'
  # quoting; anything unquoted is taken literally as-is.
  local file="$1" key="$2" line val
  line="$(grep -E "^${key}=" "$file" | tail -n1)" || return 1
  val="${line#*=}"
  if [[ "$val" == \"*\" && "$val" == *\" ]]; then
    val="${val#\"}"; val="${val%\"}"
  elif [[ "$val" == \'*\' && "$val" == *\' ]]; then
    val="${val#\'}"; val="${val%\'}"
  fi
  echo "$val"
}

with_timeout() {
  # Portable stand-in for GNU `timeout` (not present by default on macOS,
  # and coreutils isn't a dependency we want to require). Runs "$@" (a
  # command or a shell function), prints its combined output, returns its
  # exit code, or 124 on timeout. No stdin: it runs in the background.
  local secs="$1" tmp pid i=0; shift
  tmp="$(mktemp)"
  ( "$@" >"$tmp" 2>&1 ) &
  pid=$!
  while kill -0 "$pid" 2>/dev/null; do
    if (( i >= secs )); then
      kill -9 "$pid" 2>/dev/null
      cat "$tmp"; rm -f "$tmp"
      return 124
    fi
    sleep 1; i=$((i + 1))
  done
  wait "$pid"; local rc=$?
  cat "$tmp"; rm -f "$tmp"
  return $rc
}

source "$TARGET_DIR/lib/target.sh"

node_exec() {
  # node_exec <node> <cmd...> - node_run, capped and retried on timeout.
  # Bare `multipass exec` has been seen to hang indefinitely (see PLAN.md),
  # and a dropped ssh connection can do the same. Only pass commands that
  # are safe to run twice, since a timed-out call may still have gone
  # through. No stdin: with_timeout runs it in the background.
  local node="$1" attempt rc=0
  shift
  for attempt in 1 2 3; do
    with_timeout "${NODE_EXEC_TIMEOUT:-60}" node_run "$node" "$@" && return 0 || rc=$?
    [[ "$rc" -eq 124 ]] || return "$rc"
    echo "  (command on $node timed out, retry $attempt/3)" >&2
  done
  return 124
}

cp_exec() {
  # cp_exec <cmd...> - node_exec on the control plane.
  node_exec "$(cp_node)" "$@"
}

load_cp() {
  # Sets CP_NODE and CP_IP, or exits if the control plane doesn't exist.
  CP_NODE="$(cp_node)"
  node_exists "$CP_NODE" \
    || { echo "control plane not found — run $CLUSTER_TARGET/$TARGET_CP_SCRIPT first" >&2; exit 1; }
  CP_IP="$(node_ip "$CP_NODE")"
}

require_dokploy_api() {
  # Confirms Dokploy is reachable and the API key works. Needs load_cp.
  dokploy_api "$CP_IP" "cluster.getNodes" >/dev/null \
    || { echo "cannot reach Dokploy API on $CP_IP — run $CLUSTER_TARGET/01-dokploy-api-key.sh first" >&2; exit 1; }
}

ensure_docker() {
  # Only the control plane gets Docker via the Dokploy installer - workers
  # need it installed before they can run `docker swarm join`.
  local node="$1"
  if node_exec "$node" sh -c 'command -v docker' >/dev/null 2>&1; then
    return 0
  fi
  echo "  installing docker on $node"
  node_run "$node" bash -c 'curl -fsSL https://get.docker.com | sh'
}

dokploy_port_open() {
  curl -s -o /dev/null -m 2 "http://${1}:${DOKPLOY_PORT}"
}

install_dokploy() {
  # Installs Dokploy on the control plane, unless it's already answering.
  # Its installer runs `docker swarm init` itself, so no manual swarm
  # bootstrap. Needs load_cp.
  if dokploy_port_open "$CP_IP"; then
    echo "== Dokploy already responding on ${CP_IP}:${DOKPLOY_PORT}, skipping install"
    return 0
  fi

  local addr
  addr="$(cp_swarm_addr)"
  echo "== installing Dokploy on $CP_NODE ($CP_IP, swarm address $addr)"
  # Pin ADVERTISE_ADDR explicitly so Dokploy's own IP auto-detection (the
  # source of the #4517 join-command bug) never gets a chance to guess
  # wrong. Passed inline, not via `export`, since sudo resets the
  # environment otherwise.
  node_run "$CP_NODE" bash -c "curl -fsSL https://dokploy.com/install.sh | ADVERTISE_ADDR=${addr} sh"

  echo "== waiting for Dokploy to come up on port ${DOKPLOY_PORT}"
  for _ in $(seq 1 60); do
    dokploy_port_open "$CP_IP" && return 0
    sleep 5
  done
  if node_exec "$CP_NODE" curl -s -o /dev/null -m 2 "http://127.0.0.1:${DOKPLOY_PORT}" >/dev/null 2>&1; then
    echo "Dokploy is running on $CP_NODE, but ${CP_IP}:${DOKPLOY_PORT} isn't reachable from here — check the firewall" >&2
  else
    echo "Dokploy did not come up after 5 minutes" >&2
  fi
  exit 1
}

join_worker() {
  # join_worker <node> - joins a node with Docker into the control plane's
  # Swarm, using the join command Dokploy itself generates
  # (cluster.addWorker) rather than a manual token dance. Skips nodes that
  # are already part of a swarm. Needs load_cp.
  local node="$1" state
  state="$(node_exec "$node" docker info --format '{{.Swarm.LocalNodeState}}' 2>/dev/null || echo unknown)"
  if [[ "$state" == "active" ]]; then
    echo "== $node already part of the swarm, skipping join"
    return 0
  fi

  echo "== fetching worker join command from Dokploy (cluster.addWorker) for $node"
  local resp
  resp="$(dokploy_api "$CP_IP" "cluster.addWorker")"

  # NOTE: exact response field is unconfirmed until we hit a live instance -
  # try the likely field names, fall back to grepping the raw command out of
  # whatever comes back.
  local raw_cmd
  raw_cmd="$(echo "$resp" | jq -r '.command // .data.command // empty' 2>/dev/null || true)"
  if [[ -z "$raw_cmd" ]]; then
    raw_cmd="$(echo "$resp" | grep -o 'docker swarm join[^"]*' || true)"
  fi
  [[ -n "$raw_cmd" ]] || { echo "could not extract join command from Dokploy response: $resp" >&2; return 1; }

  local token
  token="$(echo "$raw_cmd" | grep -oE 'SWMTKN-[A-Za-z0-9.-]+')"
  [[ -n "$token" ]] || { echo "could not extract swarm token from: $raw_cmd" >&2; return 1; }

  local swarm_addr advertised_ip
  swarm_addr="$(cp_swarm_addr)"
  advertised_ip="$(echo "$raw_cmd" | grep -oE '[0-9]{1,3}(\.[0-9]{1,3}){3}:2377' | cut -d: -f1 || true)"
  if [[ "$advertised_ip" != "$swarm_addr" ]]; then
    echo "== Dokploy#4517: generated join IP ($advertised_ip) != actual control-plane address ($swarm_addr), correcting"
  fi

  # Always rebuild against the known-good address rather than trust
  # whatever Dokploy embedded (see architecture note in PLAN.md).
  echo "== joining $node to the swarm"
  node_run "$node" docker swarm join --token "$token" "${swarm_addr}:2377"
}

dokploy_api_key() {
  if [[ -n "${DOKPLOY_API_KEY:-}" ]]; then
    echo "$DOKPLOY_API_KEY"
  elif [[ -f "$API_KEY_FILE" ]]; then
    cat "$API_KEY_FILE"
  else
    echo "no Dokploy API key found (set DOKPLOY_API_KEY or run $CLUSTER_TARGET/01-dokploy-api-key.sh --api-key <key>)" >&2
    exit 1
  fi
}

dokploy_api() {
  # dokploy_api <cp_ip> <endpoint> [extra curl args...]
  # -f: without this, curl exits 0 on any HTTP response including 401/403/5xx
  # (only transport-level failures count), so a rejected/expired API key
  # would silently read as "success" to every caller checking the exit code.
  local ip="$1" endpoint="$2"; shift 2
  curl -sSf -H "x-api-key: $(dokploy_api_key)" \
    "http://${ip}:${DOKPLOY_PORT}/api/${endpoint}" "$@"
}
