#!/usr/bin/env bash
# Shared config and helpers, sourced by every script in this chain.
#
# Target-agnostic: how nodes are created and reached comes from
# $CLUSTER_TARGET/lib/target.sh - local/ (multipass VMs on this machine) or
# remote/ (already-provisioned servers over ssh). The scripts in those two
# folders set CLUSTER_TARGET; the shared steps in steps/ only ever go
# through the interface below, so they run unchanged against either.
#
# Target interface (see local/lib/target.sh, remote/lib/target.sh):
#   TARGET_CP_SCRIPT, TARGET_WORKERS_SCRIPT - the target's 00 / 02 scripts,
#                                  named in error messages
#   target_require               - checks the target's own host tools
#   cp_node                      - the control plane's node name
#   worker_nodes                 - the existing worker nodes, one per line
#   node_exists <node>
#   node_ip <node>               - the IPv4 address this machine reaches it on
#   cp_swarm_addr                - the address workers reach the control
#                                  plane on (Swarm's advertise address)
#   cp_connect                   - sets DOKPLOY_URL, REGISTRY_URL and
#                                  OPENBAO_URL: where this machine reaches
#                                  those services on the control plane
#   cp_ui_hint <port> <path>     - how a person opens one of them in a
#                                  browser
#   node_wait_ready <node>       - blocks until it's reachable and cloud-init
#                                  (if any) is done
#   node_run <node> <cmd...>     - runs a command as root there, uncapped,
#                                  with stdin/stdout passed through
#   node_copy <file> <node> <path> - copies a local file there
#   node_hint <node>             - how a person runs a root command there,
#                                  for error messages
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

case "${CLUSTER_TARGET:-}" in
  local|remote) ;;
  *) echo "CLUSTER_TARGET must be 'local' or 'remote' (got '${CLUSTER_TARGET:-}') — run the scripts in local/ or remote/, not steps/ directly" >&2
     exit 1 ;;
esac
TARGET_DIR="$ROOT_DIR/$CLUSTER_TARGET"

DOKPLOY_PORT=3000
REGISTRY_PORT=5000
OPENBAO_PORT=8200

# Everything the chain generates is tied to one cluster, so it lives per
# target: a local test cluster and a remote one never overwrite each other's
# keys. Gitignored. local/teardown.sh and remote/forget.sh remove it.
STATE_DIR="$ROOT_DIR/.state/$CLUSTER_TARGET"
mkdir -p "$STATE_DIR"
chmod 700 "$ROOT_DIR/.state" "$STATE_DIR"
# Dokploy's API key. Written by 01-dokploy-api-key.sh.
API_KEY_FILE="$STATE_DIR/dokploy-api-key"
# Generated by 03-setup-registry.sh.
REGISTRY_CREDS_FILE="$STATE_DIR/registry-credentials"
# OpenBao's init response (root token, recovery key). Written by
# 05-setup-openbao.sh.
OPENBAO_INIT_FILE="$STATE_DIR/openbao-init.json"
# The web app's first admin. Generated by 07-deploy-web-app.sh.
WEB_APP_CREDS_FILE="$STATE_DIR/web-app-credentials"

require() {
  for cmd in "$@"; do
    command -v "$cmd" >/dev/null 2>&1 || { echo "missing required command: $cmd" >&2; exit 1; }
  done
}

env_file_value() {
  # env_file_value <file> <key> - extract KEY=value from a simple env file
  # WITHOUT sourcing/executing it. A strong random password can easily
  # contain shell-special characters ($, !, `, etc.) - `source`-ing the
  # file would let bash try to interpret those instead of treating the
  # value as plain text. Only strips one layer of matching "..."/'...'
  # quoting; anything unquoted is taken literally as-is.
  local file="$1" key="$2" line val
  line="$(grep -E "^${key}=" "$file" | tail -n1)" || return 1
  val="${line#*=}"
  if [[ "$val" == \"*\" && "$val" == *\" ]]; then
    val="${val#\"}"; val="${val%\"}"
  elif [[ "$val" == \'*\' && "$val" == *\' ]]; then
    val="${val#\'}"; val="${val%\'}"
  fi
  echo "$val"
}

with_timeout() {
  # Portable stand-in for GNU `timeout` (not present by default on macOS,
  # and coreutils isn't a dependency we want to require). Runs "$@" (a
  # command or a shell function), prints its output and errors (kept apart,
  # so warnings never end up in a captured value), returns its exit code,
  # or 124 on timeout. No stdin: it runs in the background.
  local secs="$1" out err pid i=0 rc=0; shift
  out="$(mktemp)"; err="$(mktemp)"
  ( "$@" >"$out" 2>"$err" ) &
  pid=$!
  while kill -0 "$pid" 2>/dev/null; do
    if (( i >= secs )); then
      # Its children too (e.g. the ssh a function ran), which would
      # otherwise live on: found first, killed after it, so it can't
      # report their deaths.
      local kids
      kids="$(pgrep -P "$pid" 2>/dev/null || true)"
      kill -9 "$pid" 2>/dev/null || true
      [[ -z "$kids" ]] || kill -9 $kids 2>/dev/null || true
      wait "$pid" 2>/dev/null || true
      cat "$out"; cat "$err" >&2; rm -f "$out" "$err"
      return 124
    fi
    sleep 1; i=$((i + 1))
  done
  wait "$pid" || rc=$?
  cat "$out"; cat "$err" >&2; rm -f "$out" "$err"
  return $rc
}

ON_EXIT=()
on_exit() {
  # on_exit <command> - runs it when the script exits, after any registered
  # before it. A plain `trap ... EXIT` would replace the others.
  ON_EXIT+=("$1")
  trap 'for _c in "${ON_EXIT[@]}"; do eval "$_c" || true; done' EXIT
}

source "$TARGET_DIR/lib/target.sh"

node_exec() {
  # node_exec <node> <cmd...> - node_run, capped and retried on timeout.
  # Bare `multipass exec` has been seen to hang indefinitely (see PLAN.md),
  # and a dropped ssh connection can do the same. Only pass commands that
  # are safe to run twice, since a timed-out call may still have gone
  # through. No stdin: with_timeout runs it in the background.
  local node="$1" attempt rc=0
  shift
  for attempt in 1 2 3; do
    with_timeout "${NODE_EXEC_TIMEOUT:-60}" node_run "$node" "$@" && return 0 || rc=$?
    [[ "$rc" -eq 124 ]] || return "$rc"
    echo "  (command on $node timed out, retry $attempt/3)" >&2
  done
  return 124
}

cp_exec() {
  # cp_exec <cmd...> - node_exec on the control plane.
  node_exec "$(cp_node)" "$@"
}

load_cp() {
  # Sets CP_NODE and CP_IP, and DOKPLOY_URL, REGISTRY_URL and OPENBAO_URL
  # (cp_connect), or exits if the control plane doesn't exist.
  CP_NODE="$(cp_node)"
  node_exists "$CP_NODE" \
    || { echo "control plane not found — run $CLUSTER_TARGET/$TARGET_CP_SCRIPT first" >&2; exit 1; }
  CP_IP="$(node_ip "$CP_NODE")"
  cp_connect
}

require_dokploy_api() {
  # Confirms Dokploy is reachable and the API key works. Needs load_cp.
  dokploy_api "cluster.getNodes" >/dev/null \
    || { echo "cannot reach Dokploy API at $DOKPLOY_URL — run $CLUSTER_TARGET/01-dokploy-api-key.sh first" >&2; exit 1; }
}

node_run_apt() {
  # node_run_apt <node> <shell command> - runs a command that installs
  # packages. A fresh Ubuntu server starts its daily apt run within minutes
  # of booting, and an installer that meets its lock fails outright: pause
  # the timers, wait for a run in progress, and let apt itself wait on the
  # lock (DPkg::Lock::Timeout) for anything that still slips in.
  local node="$1" cmd="$2" prelude
  prelude='
set -eo pipefail
systemctl stop apt-daily.timer apt-daily-upgrade.timer 2>/dev/null || true
apt_conf="$(mktemp)"
trap '"'"'systemctl start apt-daily.timer apt-daily-upgrade.timer 2>/dev/null || true; rm -f "$apt_conf"'"'"' EXIT
for _ in $(seq 1 120); do
  systemctl is-active --quiet apt-daily.service apt-daily-upgrade.service || break
  echo "  (waiting for the system'"'"'s own apt run to finish)" >&2
  sleep 5
done
echo "DPkg::Lock::Timeout \"600\";" >"$apt_conf"
export APT_CONFIG="$apt_conf" DEBIAN_FRONTEND=noninteractive
'
  node_run "$node" bash -c "${prelude}${cmd}"
}

ensure_docker() {
  # Only the control plane gets Docker via the Dokploy installer - workers
  # need it installed before they can run `docker swarm join`.
  local node="$1"
  if node_exec "$node" sh -c 'command -v docker' >/dev/null 2>&1; then
    return 0
  fi
  echo "  installing docker on $node"
  node_run_apt "$node" 'curl -fsSL https://get.docker.com | sh'
}

check_container_dns() {
  # check_container_dns <node> - containers get their DNS servers from
  # Docker, not from the node, and when none of the node's are usable in a
  # container, builds fail minutes in on the first download. Fail here
  # instead, saying why.
  local node="$1"
  echo "== checking DNS inside containers on $node"
  if NODE_EXEC_TIMEOUT=180 node_exec "$node" sh -c \
      'docker pull -q busybox:1.37 >/dev/null && docker run --rm busybox:1.37 nslookup -type=a proxy.golang.org >/dev/null; rc=$?; docker image rm busybox:1.37 >/dev/null 2>&1; exit $rc'; then
    return 0
  fi
  echo "containers on $node can't resolve names. Their DNS servers are the node's upstream ones:" >&2
  node_exec "$node" sh -c 'grep ^nameserver /run/systemd/resolve/resolv.conf 2>/dev/null || grep ^nameserver /etc/resolv.conf' >&2 || true
  echo "check that those answer from inside a container (e.g. no firewall on outbound port 53), or set \"dns\" in /etc/docker/daemon.json on $node and restart docker" >&2
  return 1
}

dokploy_port_open() {
  curl -s -o /dev/null -m 2 "$DOKPLOY_URL"
}

install_dokploy() {
  # Installs Dokploy on the control plane, unless it's already there. Its
  # installer runs `docker swarm init` itself, so no manual swarm
  # bootstrap. Needs load_cp.
  #
  # Checked on the node, not by whether the port answers from here: the
  # installer starts with `docker swarm leave --force`, so re-running it
  # because a firewall hid a running Dokploy would throw every worker out
  # of the swarm.
  if node_exec "$CP_NODE" sh -c 'command -v docker >/dev/null && docker service inspect dokploy >/dev/null 2>&1'; then
    echo "== Dokploy already installed on $CP_NODE, skipping install"
  else
    local addr
    addr="$(cp_swarm_addr)"
    echo "== installing Dokploy on $CP_NODE ($CP_IP, swarm address $addr)"
    # Pin ADVERTISE_ADDR explicitly so Dokploy's own IP auto-detection (the
    # source of the #4517 join-command bug) never gets a chance to guess
    # wrong. Passed inline, not via `export`, since sudo resets the
    # environment otherwise.
    node_run_apt "$CP_NODE" "curl -fsSL https://dokploy.com/install.sh | ADVERTISE_ADDR=${addr} sh"
  fi

  echo "== waiting for Dokploy to answer at $DOKPLOY_URL"
  for _ in $(seq 1 60); do
    dokploy_port_open && return 0
    sleep 5
  done
  if node_exec "$CP_NODE" curl -s -o /dev/null -m 2 "http://127.0.0.1:${DOKPLOY_PORT}" >/dev/null 2>&1; then
    echo "Dokploy is running on $CP_NODE, but $DOKPLOY_URL isn't reachable from here — check the firewall" >&2
  else
    echo "Dokploy did not come up after 5 minutes: $(node_hint "$CP_NODE") docker service ps dokploy --no-trunc" >&2
  fi
  exit 1
}

join_worker() {
  # join_worker <node> - joins a node with Docker into the control plane's
  # Swarm, using the join command Dokploy itself generates
  # (cluster.addWorker) rather than a manual token dance. Skips nodes that
  # are already part of a swarm. Needs load_cp.
  local node="$1" state
  state="$(node_exec "$node" docker info --format '{{.Swarm.LocalNodeState}}' 2>/dev/null || echo unknown)"
  if [[ "$state" == "active" ]]; then
    echo "== $node already part of the swarm, skipping join"
    return 0
  fi

  echo "== fetching worker join command from Dokploy (cluster.addWorker) for $node"
  local resp
  resp="$(dokploy_api "cluster.addWorker")"

  # NOTE: exact response field is unconfirmed until we hit a live instance -
  # try the likely field names, fall back to grepping the raw command out of
  # whatever comes back.
  local raw_cmd
  raw_cmd="$(echo "$resp" | jq -r '.command // .data.command // empty' 2>/dev/null || true)"
  if [[ -z "$raw_cmd" ]]; then
    raw_cmd="$(echo "$resp" | grep -o 'docker swarm join[^"]*' || true)"
  fi
  [[ -n "$raw_cmd" ]] || { echo "could not extract join command from Dokploy response: $resp" >&2; return 1; }

  local token
  token="$(echo "$raw_cmd" | grep -oE 'SWMTKN-[A-Za-z0-9.-]+')"
  [[ -n "$token" ]] || { echo "could not extract swarm token from: $raw_cmd" >&2; return 1; }

  local swarm_addr advertised_ip
  swarm_addr="$(cp_swarm_addr)"
  advertised_ip="$(echo "$raw_cmd" | grep -oE '[0-9]{1,3}(\.[0-9]{1,3}){3}:2377' | cut -d: -f1 || true)"
  if [[ "$advertised_ip" != "$swarm_addr" ]]; then
    echo "== Dokploy#4517: generated join IP ($advertised_ip) != actual control-plane address ($swarm_addr), correcting"
  fi

  # Always rebuild against the known-good address rather than trust
  # whatever Dokploy embedded (see architecture note in PLAN.md).
  echo "== joining $node to the swarm"
  node_run "$node" docker swarm join --token "$token" "${swarm_addr}:2377"
}

dokploy_api_key() {
  if [[ -n "${DOKPLOY_API_KEY:-}" ]]; then
    echo "$DOKPLOY_API_KEY"
  elif [[ -f "$API_KEY_FILE" ]]; then
    cat "$API_KEY_FILE"
  else
    echo "no Dokploy API key found (set DOKPLOY_API_KEY or run $CLUSTER_TARGET/01-dokploy-api-key.sh --api-key <key>)" >&2
    exit 1
  fi
}

dokploy_api() {
  # dokploy_api <endpoint> [extra curl args...] - needs load_cp.
  # -f: without this, curl exits 0 on any HTTP response including 401/403/5xx
  # (only transport-level failures count), so a rejected/expired API key
  # would silently read as "success" to every caller checking the exit code.
  # The key goes in through a file descriptor rather than argv, so it
  # doesn't show up in `ps`.
  local endpoint="$1"; shift
  curl -sSf -H @<(printf 'x-api-key: %s\n' "$(dokploy_api_key)") \
    "${DOKPLOY_URL}/api/${endpoint}" "$@"
}
